;;;; -*- Mode: Lisp; indent-tabs-mode: nil -*-

(in-package :hemlock.term)

(defun face-attrs-equal (a b)
  (cond
    ((and (null a) (null b)) t)
    ((or (null a) (null b)) nil)
    (t (and (equal (face-fg a) (face-fg b))
            (equal (face-bg a) (face-bg b))
            (eq (face-bold a) (face-bold b))
            (eq (face-faint a) (face-faint b))
            (eq (face-italic a) (face-italic b))
            (eq (face-underline a) (face-underline b))
            (eq (face-inverse a) (face-inverse b))
            (eq (face-conceal a) (face-conceal b))
            (eq (face-crossed a) (face-crossed b))
            (equal (face-underline-color a) (face-underline-color b))
            (eq (face-blink a) (face-blink b))))))

(defun face-attrs-to-plist (face)
  (when face
    (let ((props nil))
      (when (face-bold face)
        (push t props) (push :bold props))
      (when (face-faint face)
        (push t props) (push :faint props))
      (when (face-italic face)
        (push t props) (push :italic props))
      (when (face-underline face)
        (push t props) (push :underline props))
      (when (face-crossed face)
        (push t props) (push :strike-through props))
      (when (face-inverse face)
        (push t props) (push :inverse props))
      (let ((fg (resolve-color (face-fg face)))
            (bg (resolve-color (face-bg face))))
        (when (face-inverse face)
          (rotatef fg bg))
        (when (face-conceal face)
          (setf fg bg))
        (when fg (push fg props) (push :fg props))
        (when bg (push bg props) (push :bg props)))
      props)))

(defun resolve-color (color)
  (cond
    ((null color) nil)
    ((integerp color) color)
    ((and (listp color) (= (length color) 3))
     color)
    (t nil)))

(defun term-render-line (term y)
  (let* ((w (term-width term))
         (row (aref (term-grid term) y))
         (chars (make-string w :initial-element #\Space))
         (font-changes nil)
         (prev-face nil))
    (dotimes (x w)
      (let* ((cell (aref row x))
             (ch (cell-char cell))
             (face (cell-face cell)))
        (setf (schar chars x) (if (graphic-char-p ch) ch #\Space))
        (unless (face-attrs-equal face prev-face)
          (push (list x (face-attrs-to-plist face)) font-changes)
          (setf prev-face face))))
    (values chars (nreverse font-changes))))

(defun term-dump-to-string (term)
  (with-output-to-string (s)
    (dotimes (y (term-height term))
      (let ((row (aref (term-grid term) y)))
        (dotimes (x (term-width term))
          (write-char (cell-char (aref row x)) s)))
      (unless (= y (1- (term-height term)))
        (terpri s)))))

(defun term-dump-row-string (term y)
  (let* ((w (term-width term))
         (row (aref (term-grid term) y))
         (s (make-string w)))
    (dotimes (x w s)
      (setf (schar s x) (cell-char (aref row x))))))

(defun emit-sgr-string (face)
  (if (null face)
      (format nil "~C[0m" #\Escape)
      (let ((codes nil))
        (when (face-bold face) (push "1" codes))
        (when (face-faint face) (push "2" codes))
        (when (face-italic face) (push "3" codes))
        (when (face-underline face) (push "4" codes))
        (when (face-inverse face) (push "7" codes))
        (when (face-crossed face) (push "9" codes))
        (let ((fg (if (face-inverse face) (face-bg face) (face-fg face)))
              (bg (if (face-inverse face) (face-fg face) (face-bg face))))
          (when (face-conceal face)
            (setf fg bg))
          (when fg
            (push (emit-color-code fg 38) codes))
          (when bg
            (push (emit-color-code bg 48) codes)))
        (if codes
            (format nil "~C[~{~A~^;~}m" #\Escape (nreverse codes))
            (format nil "~C[0m" #\Escape)))))

(defun emit-color-code (color base)
  (cond
    ((and (integerp color) (<= 0 color 7))
     (format nil "~D" (+ base (- 38 38) color)))
    ((and (integerp color) (<= 8 color 15))
     (format nil "~D" (+ (if (= base 38) 90 100) (- color 8))))
    ((and (integerp color) (<= 0 color 255))
     (format nil "~D;5;~D" base color))
    ((and (listp color) (= (length color) 3))
     (format nil "~D;2;~D;~D;~D" base
             (first color) (second color) (third color)))
    (t (format nil "~D" (+ base (- 38 38) 9)))))

(defun term-render-ansi-line (term y)
  (let* ((w (term-width term))
         (row (aref (term-grid term) y))
         (prev-face nil))
    (with-output-to-string (s)
      (dotimes (x w)
        (let* ((cell (aref row x))
               (ch (cell-char cell))
               (face (cell-face cell)))
          (unless (face-attrs-equal face prev-face)
            (write-string (emit-sgr-string face) s)
            (setf prev-face face))
          (write-char (if (graphic-char-p ch) ch #\Space) s)))
      (write-string (format nil "~C[0m" #\Escape) s))))
